export enum STATUSES {
  SUCCESS = 'success',
  ERROR = 'error',
}

export enum ERROR_CODES_COMMON {
  INCORRECT_LOGIN = 1,
  INCORRECT_APIKEY,
  SERVER_ERROR,
  VALIDATION_ERROR,
  OBJECT_NOT_FOUND,
  INCORRECT_REQUEST,
  MISSING_REQUIRED_PARAM,
}

export enum ERROR_CODES_CARDS_ACTIVATION {
  CARD_NOT_EXISTS = 16,
  CARD_ALREADY_ACTIVATED,
  CARD_ACTIVATED_BY_ANOTHER_USER,
}

export type ERROR_CODES = ERROR_CODES_COMMON & ERROR_CODES_CARDS_ACTIVATION;
